title: Ahmadou Ndiaye
logo: /assets/![image](https://github.com/user-attachments/assets/6da1a9c4-c02e-4df2-be50-ad7bf4d394f0)/headshot_circle.png
description: text bellow image
show_downloads: true
theme: jekyll-theme-minimal
